[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@fhenixprotocol/=lib/fhenix-protocol/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

# Compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Network configurations
[rpc_endpoints]
local = "http://localhost:8545"
fhenix_testnet = "${FHENIX_RPC_URL}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
fhenix = { key = "${FHENIX_API_KEY}", url = "https://explorer.fhenix.zone/api" }

# Test settings
[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x3e8"

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false

# Gas reports
gas_reports = ["AlphaEngineSubscription", "FHEAddressEncryption"]

# Formatting
line_length = 120
tab_width = 4
bracket_spacing = true
quote_style = "double"

# CI profile for faster compilation
[profile.ci]
optimizer = false
fuzz = { runs = 100 }

# Production profile with max optimization
[profile.production]
optimizer = true
optimizer_runs = 10000
via_ir = true